// tsx - typescript and XML
// jsx - javascript and XML
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { HelloComponent } from '../components/HelloComponent'
import styles from '../styles/Home.module.css'
import { PrismaClient, User } from '@prisma/client'
const prisma = new PrismaClient()

const Home: NextPage = ({ users }: {users: User[]}) => {
  console.log();
  
  return (
    <div>
      <Head>
        <title>Hello world app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HelloComponent />
      <ul>
        {users.map(user => {
          return <li>
            <span>Email: {user.email}</span>
            <span>name: {user.name}</span>
          </li>
        })}
        {[<span>El 1</span>, <span>El 2</span>]}
      </ul>
      <Link href={'/about'}>Go to About</Link>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  const users = await prisma.user.findMany()
  return {
    props: { users: users.map(({ name, email }) => ({ name, email })) }, // will be passed to the page component as props
  }
}
